port to use git-sh-setup and update interface (version bump)
add DESTDIR support
install text version of manpage to /usr/share/doc/git-track/git-track.txt

diff --git a/git-track b/git-track
--- a/git-track
+++ b/git-track
@@ -1,28 +1,5 @@
 #!/bin/sh
 
-## version: 1.0
-
-## git track: a simple shell script to ease the unnecessarily complex task of
-## tracking a branch, i.e., setting up a local branch to track a remote one, all
-## in one go.
-## 
-## In other words, set up <local_branch> to track
-## refs/remote/<remote>/<remote_branch>
-## 
-##     Usage: git track [-v] [-n] [-f] [-b <remote_branch>] [[<remote>] <local_branch>]
-##        or: git track [-v] [-n] -d <local_branch>
-## 
-##     <local_branch> is the local branch. If -b <remote_branch> is not used,
-##     <remote_branch> is <local_branch>
-## 
-##     <remote> is the remote to track to -- defaults to origin
-## 
-##     -v -- print each command as it is run.
-##     -n -- don't run any commands, just print them.
-##     -f -- don't do any checks on whether <local_branch> is tracking a branch
-##           already.
-##     -d -- stop <local_branch> from tracking anything.
-##
 ## git track Copyright 2010 Gavin Beatty <gavinbeatty@gmail.com>.
 ## 
 ## This program is free software: you can redistribute it and/or modify
@@ -38,20 +15,30 @@
 ## You can find the GNU General Public License at:
 ## http://www.gnu.org/licenses/
 
-set -u
 set -e
 
-usage() {
-    echo "Usage: git track [-v] [-n] [-f] [-b <remote_branch>] [[<remote>] <local_branch>]"
-    echo "   or: git track [-v] [-n] -d <local_branch>"
-}
-die() {
-    echo "error: $@" >&2
-    exit 1
+SUBDIRECTORY_OK=Yes
+OPTIONS_KEEPDASHDASH=""
+OPTIONS_SPEC="\
+git track [options] [<remote>]
+git track [options] -l <local_branch> -d
+--
+v,verbose   print each command as it is run
+n,dry-run   don't run any commands, just print them
+f,force     don't do any checks on whether <local_branch> is tracking a branch already
+r,remote-branch=    the remote branch defaults to the local branch name - use this to override
+l,local-branch= the local branch whose tracking information we will change
+d,delete    delete tracking configuration for <local_branch>
+version print version info in 'git track version \$version' format"
+
+. "$(git --exec-path)/git-sh-setup"
+
+version_print() {
+    echo "git track version 2.0"
 }
 
 doit() {
-    if test -n "$verbose" ; then
+    if test "$verbose" -gt 0 ; then
         echo "$@"
     fi
     if test -z "$dryrun" ; then
@@ -62,95 +49,108 @@ full_name() {
     git rev-parse --symbolic-full-name "$@"
 }
 
+die_head() {
+    die "Cannot operate with detached HEAD without being given <local_branch>"
+}
+
+default_local_branch() {
+    lb_="$(full_name "HEAD")"
+    lb_="$(echo "$lb_" | sed -e 's|^refs/heads/||')"
+    echo "$lb_"
+}
+
 main() {
-    dryrun=""
-    force=""
-    verbose=""
-    delete=""
-    if ! type "git" 1>/dev/null 2>&1 ; then
-        die "Please install git."
-    fi
-    if ! git rev-parse --git-dir >/dev/null 2>&1 ; then
-        die "Not a git repository (or any of the parent directories)"
+    has_head=""
+    if git rev-parse --verify -q "HEAD" >/dev/null ; then
+        has_head=yes
     fi
 
-    while getopts ":hnfvdb:" opt ; do
-        case "$opt" in
-        h)
-            usage
+    verbose=0
+    dry_run=""
+    force=""
+    delete=""
+    lbranch=""
+    rbranch=""
+    while test $# -ne 0 ; do
+        case "$1" in
+        -v|--verbose)
+            verbose="$(expr "$verbose" "+" 1)"
+            ;;
+        -n|--dry-run)
+            verbose="$(expr "$verbose" "+" 1)"
+            dry_run=true
+            ;;
+        -f|--force)
+            force=true
+            ;;
+        -d|--delete)
+            delete=true
+            ;;
+        -r|--remote-branch)
+            rbranch="$2"
+            shift
+            ;;
+        -l|--local-branch)
+            lbranch="$2"
+            shift
+            ;;
+        --version)
+            version_print
             exit 0
             ;;
-        n)
-            dryrun="true"
-            verbose="true"
-            ;;
-        f)
-            force="true"
-            ;;
-        v)
-            verbose="true"
-            ;;
-        d)
-            delete="true"
-            ;;
-        b)
-            remote_branch="$OPTARG"
-            ;;
-        \?)
-            die "invalid option: -${OPTARG}"
+        --)
+            shift
+            break
             ;;
         *)
-            die "invalid getopts return: $opt"
+            usage
             ;;
         esac
+        shift
     done
-    shift "$(expr "$OPTIND" - 1)"
-    OPTIND=1
 
     if test -n "$delete" ; then
-        if test $# -gt 0 ; then
-            local_branch="$1"
-        else
-            local_branch="$(full_name "HEAD")"
-            local_branch="$(echo "$local_branch" | sed -e 's|^refs/heads/||')"
+        if test -z "${lbranch}" ; then
+            test -z "$has_head" && die_head
+            lbranch="$(default_local_branch)"
         fi
         # don't worry about deleting the section - an empty section is ok
         # and deleting other options in the section by removing it entirely
         # is too destructive
-        doit git config --unset "branch.${local_branch}.remote" || e=$?
-        doit git config --unset "branch.${local_branch}.merge" || e=$?
+        doit git config --unset "branch.${lbranch}.remote" || e=$?
+        doit git config --unset "branch.${lbranch}.merge" || e=$?
     else
         if test $# -gt 0 ; then
             remote="$1"
         fi
-        if test $# -gt 1 ; then
-            local_branch="$2"
-        else
-            local_branch="$(full_name "HEAD")"
-            local_branch="$(echo "$local_branch" | sed -e 's|^refs/heads/||')"
+        if test -z "${lgiven}" ; then
+            test -z "$has_head" && die_head
+            lbranch="$(default_local_branch)"
         fi
         remote="${remote:-origin}"
-        if test -z "${remote_branch:-}" ; then
-            remote_branch="$local_branch"
+        if test -z "$rgiven" ; then
+            rbranch="$lbranch"
         else
-            remote_branch="$(echo "$remote_branch" | sed -e 's|^refs/heads/||')"
+            rbranch="$(echo "$rbranch" | sed -e 's|^refs/heads/||')"
         fi
 
         if test -z "$force" ; then
-            remote_ref="$(git show-ref "remotes/${remote}/${remote_branch}" || e=$?)"
+            remote_ref="$(git show-ref "remotes/${remote}/${rbranch}" || e=$?)"
             if test -z "$remote_ref" ; then
-                die "Remote branch ${remote_branch} does not exist on ${remote}."
+                die "Remote branch '${rbranch}' does not exist on '${remote}'."
             fi
-            remote_config="$(git config "branch.${local_branch}.merge")"
-            if test -n "$remote_config" ; then
-                die "Local branch ${local_branch} is already tracking ${remote_config}."
+            track_merge="$(git config "branch.${lbranch}.merge" || e=$?)"
+            if test -n "$track_merge" ; then
+                track_remote="$(git config "branch.${lbranch}.remote" || e=$?)"
+                die "Local branch '${lbranch}' is already tracking '${track_merge}' on '${track_remote}'."
             fi
         fi
 
-        doit git config "branch.${local_branch}.remote" "$remote"
-        doit git config "branch.${local_branch}.merge" "refs/heads/${remote_branch}"
+        doit git config "branch.${lbranch}.remote" "$remote"
+        doit git config "branch.${lbranch}.merge" "refs/heads/${rbranch}"
     fi
 }
+
 
 trap "echo \"caught SIGINT\" ; exit 1 ;" INT
 trap "echo \"caught SIGTERM\" ; exit 1 ;" TERM
